### ISSUE TITLE
访问成功无法连接

### ISSUE THREAD

**Issue by xuyang1152** [Tas9er/ByPassGodzilla#1]
访问成功了 ，但是无法连接

**Comment by Tas9er** [comment]
你好！查看一下是不是密钥和加密器已经加密载荷选择错了！顺便BP抓包看一下

**Comment by xuyang1152** [comment]
![image](https://user-images.githubusercontent.com/30486600/199911399-fea9ab8c-e3ca-4cf7-89c6-933610b37dcc.png)
生成码如下
![image](https://user-images.githubusercontent.com/30486600/199911446-490585ca-3b0c-4526-9a4d-d57c32621767.png)

但是连接就是报错
![image](https://user-images.githubusercontent.com/30486600/199911537-7cad95c3-6c00-49c4-96a7-de01e9f72827.png)

**Comment by xuyang1152** [comment]
抓包也只能读取到当前页面
![image](https://user-images.githubusercontent.com/30486600/199912276-3e39a235-ad72-487a-8b54-c3e27a65a320.png)

**Comment by Tas9er** [comment]
你好！建议换一个PHP环境试一下，PHP马受PHP环境影响！例如upload_labs或者其他环境！

**Comment by xuyang1152** [comment]
好的 谢谢您， 我尝试使用默认的马，是可以连接成功。
![image](https://user-images.githubusercontent.com/30486600/199913864-3d72df56-f994-4a48-a5a7-c5a1f8a0bb94.png)

**Comment by Tas9er** [comment]
部分函数受环境影响，实战的情况下，尤其是PHP的马，需要多尝试

**Comment by Tas9er** [comment]
试了一下环境，目前一切正常！
![1667546093193](https://user-images.githubusercontent.com/57090266/199914724-0e7f3bbe-5e4f-4441-b68b-a7757cf61fa5.jpg)

**Comment by xuyang1152** [comment]
能请问下老师您用的远控的版本是4.0吗，或者能麻烦您传个马我尝试一下？
感谢老师百忙中回答我的问题，谢谢

**Comment by Tas9er** [comment]
[官网](https://github.com/BeichenDream/Godzilla) 作者4.0.1版本

**Comment by xuyang1152** [comment]
感谢老师，这边测试成功了，是php版本的问题，适用于php5.3.29 和5.5.9 ，php的 7.3.4版本不适用；
